
CREATE TABLE ADDRESS (
	ADDRESS_ID INT PRIMARY KEY NOT NULL,
	STREET VARCHAR(100),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	ZIP_CODE VARCHAR(10)
);

CREATE TABLE CUSTOMER (
	CUSTOMER_ID INT PRIMARY KEY NOT NULL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	SSN INT NOT NULL,
	ADDRESS_ID INT NOT NULL, 
	EMAIL_ADDRESS VARCHAR(100),
	PHONE_NUMBER INT,
	FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);


CREATE TABLE CHECKING_ACCOUNT(
	ACCOUNT_NUMBER INT PRIMARY KEY NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	ROUTING_NUMBER INT NOT NULL,
	BALANCE DECIMAL(10, 2) NOT NULL,
	WITHDRAWAL_LIMIT DECIMAL(10, 2),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
	CONSTRAINT CHECK_BALANCE CHECK (BALANCE >= 0)
);

CREATE TABLE SAVINGS_ACCOUNT(
	ACCOUNT_NUMBER INT PRIMARY KEY NOT NULL,\
	CUSTOMER_ID INT NOT NULL,
	ROUTING_NUMBER INT NOT NULL,
	BALANCE DECIMAL(10, 2) NOT NULL,
	MINIMUM_BALANCE DECIMAL(10, 2),
	INTEREST_RATE DECIMAL(5, 2),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID INT PRIMARY KEY NOT NULL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	ROLE VARCHAR(20)
);

CREATE TABLE SALARY
(
	ROLE VARCHAR(20) NOT NULL,
	SALARY  INT,
	FOREIGN KEY (ROLE) REFERENCES EMPLOYEE (ROLE)
);

CREATE TABLE CREDIT_CARD (
	CREDIT_CARD_NUMBER INT PRIMARY KEY NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	CVC VARCHAR(4) NOT NULL,
	EXPIRATION_DATE DATE NOT NULL,
	BALANCE DECIMAL(10, 2) NOT NULL,
	SPENDING_LIMIT DECIMAL(10, 2),
	INTEREST_RATE DECIMAL(5, 2),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TRANSACTION_HISTORY(
	ACCOUNT_NUMBER INT PRIMARY KEY NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	TRANSACTION_AMOUNT DECIMAL(10, 2) NOT NULL,
	TRANSACTION_DATE DATE NOT NULL,
	DEPOSIT_LIMIT INT,
	WITHDRAWAL_LIMIT INT,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE LOANS (
	LOAN_NUMBER INT PRIMARY KEY NOT NULL,
	CUSTOMER_ID INT,
	LOAN_AMOUNT DECIMAL(10, 2),
	PAYMENT_REMAINING DECIMAL(10, 2),
	MONTHLY_PAYMENT_AMOUNT DECIMAL(10, 2),
	INTEREST_RATE DECIMAL(5, 2),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
